# Generated by Django 4.0.3 on 2022-03-11 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_todo', '0002_alter_tasks_options_alter_tasks_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 21, 59, 49, 369742)),
        ),
    ]
