# Generated by Django 4.0.3 on 2022-03-12 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_todo', '0003_alter_tasks_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 15, 58, 45, 660354)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='type',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Shopping', 'Shopping'), ('Wishlist', 'Wishlist'), ('Office', 'Office'), ('Custom', 'Custom')], max_length=35),
        ),
    ]
