# Generated by Django 4.0.3 on 2022-03-13 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_todo', '0005_alter_tasks_created_at_alter_tasks_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 17, 20, 12, 497658)),
        ),
    ]
