# Generated by Django 4.0.3 on 2022-03-13 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_todo', '0006_alter_tasks_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 17, 23, 21, 499656)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='remainder',
            field=models.DateTimeField(null=True),
        ),
    ]
